-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "2736x1824@59.96", position = "1568x1440", scale = 2.00 })
hl.monitor({ output = "DP-1", mode = "2560x1440@59.97", position = "1440x288", scale = 1.25 })
hl.monitor({ output = "DVI-I-1", mode = "1920x1080@60.00", position = "3488x360", scale = 1.25 })
