-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "2736x1824@59.96", position = "-1984x256", scale = 2.00 })
hl.monitor({ output = "DP-1", mode = "2560x1440@144.00", position = "-2336x-896", scale = 1.25 })
