-- Copilot
-- TODO: Looking at moving to Sidekick. Disabling copilot chat - this file is not loaded
-- TODO: (insane): Fork CopilotChat.nvim, and modify this file to allow you to call it smokes: https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/feca60cf0ae08d866ba35cc8a95d12941ccc4f59/lua/CopilotChat/prompts.lua#L5
-- TODO: "fix" and "fix diagnostics" - https://github.com/CopilotC-Nvim/CopilotChat.nvim
--
-- local chat = require("CopilotChat")
-- local CopilotChatSelect = require("CopilotChat.select")
--
-- local function ask_copilot(prompt, selectionMethod, callback)
-- 	return function()
-- 		local question
-- 		if prompt ~= nil and prompt ~= "" then
-- 			question = prompt
-- 		else
-- 			question = vim.fn.input("Quick Chat: ")
-- 		end
-- 		-- TODO: Bail if no question
-- 		chat.ask(question, {
-- 			selection = CopilotChatSelect[selectionMethod],
-- 			callback = callback or function() end,
-- 		})
-- 	end
-- end
--
-- -- Function which uses set_keymap and ask_copilot to create the same keymap for visual and normal mode
-- local function set_copilot_ask_keymap(key, question, desc, callback)
-- 	set_keymap("n", key, ask_copilot(question, "buffer", callback), desc .. " current buffer")
-- 	set_keymap("v", key, ask_copilot(question, "visual", callback), desc .. " selection")
-- end
--
-- local function open_copilot_chat(selectionMethod)
-- 	return function()
-- 		chat.open({
-- 			selection = CopilotChatSelect[selectionMethod],
-- 		})
-- 	end
-- end
--
-- -- Open Copilot chat window fully
-- set_keymap("n", "<leader>C", open_copilot_chat("buffer"), "Open Copilot chat window")
-- set_keymap("v", "<leader>C", open_copilot_chat("visual"), "Open Copilot chat window")
--
-- -- Ask Copilot a single question
-- set_copilot_ask_keymap("<leader>cc", nil, "Open Copilot chat window")
--
-- set_keymap("n", "<leader>gd", "<cmd>CopilotChatCommit<CR>", "Generate a commit message for the current diff")
-- set_keymap("n", "<leader>gs", "<cmd>CopilotChatCommitStaged<CR>", "Generate a commit message for the staged changes")
--
-- -- Open options in telescope
--
-- local CopilotChatTelescope = require("CopilotChat.integrations.telescope")
-- -- Open help actions with telescope
-- set_keymap("n", "<leader>ch", function()
-- 	local actions = require("CopilotChat.actions").help_actions()
-- 	CopilotChatTelescope.pick(actions)
-- end, "CopilotChat - Help actions")
--
-- -- Show prompts actions with telescope
-- set_keymap("n", "<leader>cp", function()
-- 	local actions = require("CopilotChat.actions").prompt_actions()
-- 	CopilotChatTelescope.pick(actions)
-- end, "CopilotChat - Prompt actions")
--
-- -- Explain
-- set_copilot_ask_keymap("<leader>ce", "Please explain how this code works", "Ask Copilot to explain")
--
-- -- TODO: This seems inconsistent
-- -- Review
-- set_copilot_ask_keymap("<leader>cr", "Please review this code", "Ask Copilot to review") -- TODO: This doesn't add the in-line hinting like CopilotChatReview
-- --set_keymap("n", "<leader>cr", "<cmd>CopilotChatReview<CR>", "Ask copilot to review current buffer")
-- --set_keymap("v", "<leader>cr", "<cmd>CopilotChatReview<CR>", "Ask copilot to review selection")
--
-- -- Optimize
-- set_copilot_ask_keymap(
-- 	"<leader>co",
-- 	"Please optimize this code to improve performance and readablilty",
-- 	"Ask Copilot to optimize"
-- )
--
-- -- Document
-- set_copilot_ask_keymap("<leader>cd", "Please add documentation comment(s) for this code", "Ask Copilot to document")
--
-- -- Generate Tests
-- set_copilot_ask_keymap("<leader>ct", "Please generate tests for this code", "Ask Copilot to document")
--
-- -- Quick win
-- set_copilot_ask_keymap("<leader>cq", "Give me a quick win", "Ask Copilot for a quick win")
--
